
@server = http://localhost:8088

@itsEmail = its@friday.com
@itsUsername = skyblue
@itsPassword = 1234

@itsNewEmail = its@monday.com
@itsNewNickname = silver
@itsNewPassword = 4321

# 1. 헬쓰 체크로 앱이 잘 작동중인지 확인
# 2. [signup -> login -> logout -> 사용자 삭제] 이 잘 되는지 확인
# 3. [signup, login]후 사용자 정보의 Read, Update 확인

### health

GET {{server}}/monitor/health HTTP/1.1
Content-Type: application/json

### user service

# @name tempUser
POST {{server}}/v1/user/signup HTTP/1.1
Content-Type: application/json

{
  "email": "{{itsEmail}}",
  "username": "{{itsUsername}}",
  "password": "{{itsPassword}}"
}

###

@userId = {{tempUser.response.body.id}}

###

# @name tempLogin
POST {{server}}/v1//userlogin HTTP/1.1
Content-Type: application/json

{
  "username": "{{itsUsername}}",
  "password": "{{itsPassword}}"
}

###

@tempAccessToken = {{tempLogin.response.body.accessToken}}

###

DELETE {{server}}/v1/user/delete-user HTTP/1.1
Authorization: Bearer {{tempAccessToken}}
Content-Type: application/json

{
  "username": "{{itsUsername}}",
  "password": "{{itsPassword}}"
}

### user

# @name user
POST {{server}}/v1/user/signup HTTP/1.1
Content-Type: application/json

{
  "email": "{{itsEmail}}",
  "username": "{{itsUsername}}",
  "password": "{{itsPassword}}"
}

###

@userId = {{user.response.body.id}}

###

# @name login
POST {{server}}/v1/user/login HTTP/1.1
Content-Type: application/json

{
  "username": "{{itsUsername}}",
  "password": "{{itsPassword}}"
}

###

@accessToken = {{login.response.body.accessToken}}

###

GET {{server}}/v1/user/profile HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

PUT {{server}}/v1/user/update-user HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "email": "{{itsNewEmail}}",
  "nickname": "{{itsNewNickname}}",
  "oldPassword": "{{itsPassword}}",
  "newPassword": "{{itsNewPassword}}",
  "description": "new description"
}

###

POST {{server}}/v1/user/logout HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

### libro service

# @name book
POST {{server}}/v1/libro/books
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title": "질병 해방",
  "author": "피터 아티아,빌 기퍼드",
  "translator": "이한음",
  "pages": 751,
  "pubYear": 2024,
  "genre": "novel"
}

###

@bookId = {{book.response.body.id}}

###

GET {{server}}/v1/libro/books/{{bookId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

PUT {{server}}/v1/libro/books/{{bookId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "genre": "sc-fi"
}

###

DELETE {{server}}/v1/libro/books/{{bookId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

# @name book_review
POST {{server}}/v1/libro/reviews
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "bookId": {{bookId}},
    "dateRead": "2024-05-01",
    "rating": 3,
    "review": "Good"
}

###

@bookReviewId = {{book_review.response.body.id}}

###

GET {{server}}/v1/libro/reviews/{{bookReviewId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

PUT {{server}}/v1/libro/reviews/{{bookReviewId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "rating": 4
}

###

DELETE {{server}}/v1/libro/reviews/{{bookReviewId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

GET {{server}}/v1/libro/dashboard
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

GET {{server}}/v1/libro/reads?year=2024
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

GET {{server}}/v1/libro/report
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

GET {{server}}/v1/libro/books/{{bookId}}/reviews
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
