
@server = http://localhost:8088

@itsEmail = its@friday.com
@itsUsername = skyblue
@itsPassword = 1234

@itsNewEmail = its@monday.com
@itsNewNickname = silver
@itsNewPassword = 4321

### HEALTH

GET {{server}}/monitor/health HTTP/1.1
Content-Type: application/json

### USER SERVICE ###

### user

# @name user
POST {{server}}/v1/user/signup HTTP/1.1
Content-Type: application/json

{
  "email": "{{itsEmail}}",
  "username": "{{itsUsername}}",
  "password": "{{itsPassword}}"
}

###

@userId = {{user.response.body.id}}

###

# @name login
POST {{server}}/v1/user/login HTTP/1.1
Content-Type: application/json

{
  "username": "{{itsUsername}}",
  "password": "{{itsPassword}}"
}

###

@accessToken = {{login.response.body.accessToken}}

###

GET {{server}}/v1/user/profile HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

PUT {{server}}/v1/user/update-user HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "email": "{{itsNewEmail}}",
  "nickname": "{{itsNewNickname}}",
  "oldPassword": "{{itsPassword}}",
  "newPassword": "{{itsNewPassword}}",
  "description": "new description"
}

###

POST {{server}}/v1/user/logout HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

DELETE {{server}}/v1/user/delete-user HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "username": "{{itsUsername}}",
  "password": "{{itsPassword}}"
}

### LIBRO SERVICE ###

# @name book
POST {{server}}/v1/libro/books
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title": "질병 해방",
  "author": "피터 아티아,빌 기퍼드",
  "translator": "이한음",
  "pages": 751,
  "pubYear": 2024,
  "genre": "health"
}

###

@bookId = {{book.response.body.id}}

###

# @name book2
POST {{server}}/v1/libro/books
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title": "협력의 진화",
  "author": "로버트 액설로드",
  "translator": "이경식",
  "pages": 292,
  "pubYear": 2013,
  "genre": "science"
}

###

@book2Id = {{book2.response.body.id}}

###

GET {{server}}/v1/libro/books/{{bookId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

PUT {{server}}/v1/libro/books/{{bookId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "genre": "sc-fi"
}

###

DELETE {{server}}/v1/libro/books/{{bookId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

# @name book_review
POST {{server}}/v1/libro/reviews
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "bookId": {{bookId}},
    "dateRead": "2024-05-01",
    "rating": 3,
    "review": "Good"
}

###

@bookReviewId = {{book_review.response.body.id}}

###

# @name book2_review
POST {{server}}/v1/libro/reviews
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "bookId": {{book2Id}},
    "dateRead": "2025-06-12",
    "rating": 3,
    "review": "Good"
}

###

@bookReview2Id = {{book2_review.response.body.id}}

###

GET {{server}}/v1/libro/reviews/{{bookReviewId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

PUT {{server}}/v1/libro/reviews/{{bookReviewId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "rating": 4
}

###

DELETE {{server}}/v1/libro/reviews/{{bookReviewId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

GET {{server}}/v1/libro/dashboard
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

GET {{server}}/v1/libro/reads?year=2025
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

GET {{server}}/v1/libro/report
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

GET {{server}}/v1/libro/books/{{bookId}}/reviews
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

### DINERO SERVICE ###

###

# @name dinero_category
POST {{server}}/v1/dinero/categories
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "고정지출4",
  "priority": 1
}

###

@dineroCategoryId = {{dinero_category.response.body.id}}

###

PUT {{server}}/v1/dinero/categories/{{dineroCategoryId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "priority": 2
}

###

DELETE {{server}}/v1/dinero/categories/{{dineroCategoryId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

GET {{server}}/v1/dinero/categories
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

# @name expense
POST {{server}}/v1/dinero/expenses
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "categoryId": {{dineroCategoryId}},
  "dateUsed": "2025-05-07",
  "item": "점심",
  "price": 10000
}

###

@expenseId = {{expense.response.body.id}}

###

PUT {{server}}/v1/dinero/expenses/{{expenseId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "price": 12000
}

###

GET {{server}}/v1/dinero/expenses?year=2025&month=5
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

DELETE {{server}}/v1/dinero/expenses/{{expenseId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json


###

GET {{server}}/v1/dinero/report?year=2025&month=5
Authorization: Bearer {{accessToken}}
Content-Type: application/json
